### ISSUE TITLE
Promise support in 11.0.2: then(...).done is not a function

### ISSUE THREAD

**Issue by akobler** [elastic/elasticsearch-js#429]
Hi all

I just upgraded from elasticsearch package from 4.0.2 to 11.0.1 and face the following. Exactly the same code was working in 4.0.2. Now on 11.0.1 the code snippet below throws:
```
TypeError: doSearch(...).then(...).catch(...).done is not a function
```
Without the trailing done() it works. If I remove the catch() and put the done() directly after then() , the same exception gets thrown. As described here https://www.npmjs.com/package/promise, the promise library that is used in elasticsearch module provides done().

```
    doSearch(esClient)
    .then(function(data) {
        return res.status(200).json(data)
    })
    .catch(function(error) {
        return res.status(500).send()
    })
    .done()

    function doSearch(esClient) {

        return esClient.search(esRequest)
        .then(function(esResult) {

            // logging stuff

            return transformResult(esResult)
        })
    }

    function transformResult(esResult) {
        return 'result'
    }
```

Is anybody able to tell what exactly goes on here? What am I missing?

Thanks for any hint,
Andreas

**Comment by spalger** [comment]
We used to use Bluebird for internal promises, which is where the .done() method was coming from. I suggest you wrap the es6 promises were sending back with whatever promise library you're interested in (I recommend bluebird)

```js
Bluebird.resolve(client.serch(...)).done()
```
