### ISSUE TITLE
Error parsing undici module in Next.js 14 project

### ISSUE THREAD

**Issue by sleipner01** [elastic/elasticsearch-js#2207]
## 🐛 Bug Report

In a Next.js 14 project, my team and I encountered this problem Tuesday 2nd of April.
A member tried running the project after reinstalling node_modules and got the following error:

```bash
 ⨯ ./node_modules/undici/lib/web/fetch/util.js
Module parse failed: Unexpected token (884:57)
|       // 5. If object is not a default iterator object for interface,
|       //    then throw a TypeError.
>       if (typeof this !== 'object' || this === null || !(#target in this)) {
|         throw new TypeError(
|           `'next' called on an object that does not implement interface ${name} Iterator.`

Import trace for requested module:
./node_modules/undici/lib/web/fetch/util.js
./node_modules/undici/lib/web/fetch/index.js
./node_modules/undici/index.js
./node_modules/@elastic/transport/lib/connection/UndiciConnection.js
./node_modules/@elastic/transport/lib/connection/index.js
./node_modules/@elastic/transport/index.js
./node_modules/@elastic/elasticsearch/index.js
./src/search/client.ts
./src/search/search.ts
```

April 2nd both [undici](https://www.npmjs.com/package/undici?activeTab=versions) and [@elastic/transport](https://www.npmjs.com/package/@elastic/transport?activeTab=versions) had version updates.

> I managed to "mitigate" the problem by downgrading @elastic/transport to version 8.4.1. This forced undici to version 5.28.4 (looking at package-lock.json)

## To Reproduce

Using any elastic Client initialisation with Next.js 14.

 Any standard Next.js package.json containing the following:
` "@elastic/elasticsearch": "^8.12.2",`
>Having the caret character is essential to reproduce the error.

Run: `npm install`
Run: `npm run dev`

## Expected behavior

Build/run successfully

## Environment

- *node version*: 20+
- *@elastic/elasticsearch version*: 8.13.0
- *os*: macOS Sonoma 14.4
- *Next.js*: 14.1.0
- *@elastic/transport*: ^8.4.0
- *undici*: ^6.7.0

**Comment by sleipner01** [comment]
@JoshMock The upgrade resolved the problem in our project. Thanks:)

**Comment by dylanhu7** [comment]
@JoshMock After upgrading to 8.14 from 8.13, it seems this issue has resurfaced. I am also using Next 14, and undici@6.19.2

**Comment by dylanhu7** [comment]
> @JoshMock After upgrading to 8.14 from 8.13, it seems this issue has resurfaced. I am also using Next 14, and undici@6.19.2

Never mind, it seems updating to `next@14.2.5` fixed it.

**Comment by sanny085** [comment]
> > [@JoshMock](https://github.com/JoshMock) After upgrading to 8.14 from 8.13, it seems this issue has resurfaced. I am also using Next 14, and undici@6.19.2
> 
> Never mind, it seems updating to `next@14.2.5` fixed it.

After updating from "next": "14.0.4" to "next": "^14.2.5". issue resolved, Thanks @dylanhu7
