### ISSUE TITLE
ts: typesWithBodyKey no longer exists

### ISSUE THREAD

**Issue by bkuster** [elastic/elasticsearch-js#2835]
### Regression report

No longer able to build TS project after update to 9: `Cannot find module './lib/api/typesWithBodyKey' or its corresponding type declarations.` Quick look at the package: the file no longer exists.

### Last working version

8.18.2

### To reproduce

create a file `foo.ts`
```ts
import { Client } from '@elastic/elasticsearch';
```

run 
```bash
npx tsc foo.ts
``` 

### Expected behavior

i expect this to build

### Node.js version

20.18.3

### TypeScript version

5.8.3

### Elasticsearch client version

9.0.1

### Elasticsearch server version

9.0.1

### Operating system

Debian

**Comment by JoshMock** [comment]
This is [mentioned](https://www.elastic.co/docs/release-notes/elasticsearch/clients/javascript/breaking-changes) in the 9.0 breaking changes, at least indirectly. `typesWithBodyKey` is indeed no longer supported and that is intentional.

I've updated the breaking changes does in https://github.com/elastic/elasticsearch-js/pull/2839 to mention this more explicitly. If you need `typesWithBodyKey`, it is suggested to keep using an 8.x client until you are ready to remove its usage.

**Comment by bkuster** [comment]
You misunderstand, let me be more blunt:

_I_ dont wish to use the `typesWithBodyKey` _YOUR packaged release still tries to export a missing file_.

In other words, you missed a spot.

**Comment by JoshMock** [comment]
Got it, misunderstood what you meant. That was actually in https://github.com/elastic/elasticsearch-js/pull/2821 recently but a patch release has not been published since then. I'll publish 9.0.2 today with that fix.
